### ISSUE TITLE
something error when I compile

### ISSUE THREAD

**Issue by pangchenglin** [HKUST-Aerial-Robotics/ESVO#1]
when I run：catkin build esvo_time_surface esvo_core
something error happend.
Cloud you please help me to solve this problem? I' dont know how to solve it.
_______________________________________________________________________________
Errors     << esvo_core:make /home/pclin/esvo_ws/logs/esvo_core/build.make.005.log
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘vtable for YAML::BadConversion’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘YAML::detail::node_data::empty_scalar[abi:cxx11]()’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘typeinfo for YAML::BadConversion’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘YAML::detail::node_data::convert_to_map(std::shared_ptr<YAML::detail::memory_holder> const&)’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘YAML::BadConversion::~BadConversion()’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [/home/pclin/esvo_ws/devel/.private/esvo_core/lib/esvo_core/esvo_Tracking] Error 1
make[1]: *** [CMakeFiles/esvo_Tracking.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘YAML::detail::node_data::empty_scalar[abi:cxx11]()’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘typeinfo for YAML::BadConversion’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘YAML::BadConversion::~BadConversion()’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘vtable for YAML::BadConversion’未定义的引用
/home/pclin/esvo_ws/devel/.private/esvo_core/lib/libesvo_core_LIB.so：对‘YAML::detail::node_data::convert_to_map(std::shared_ptr<YAML::detail::memory_holder> const&)’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [/home/pclin/esvo_ws/devel/.private/esvo_core/lib/esvo_core/esvo_Mapping] Error 1
make[1]: *** [CMakeFiles/esvo_Mapping.dir/all] Error 2
make: *** [all] Error 2
Thanks a lot！！！

**Comment by Ethan-Zhou** [comment]
Hi @pangchenglin,
It looks like the **yaml-cpp** is not doing the work. Please double check if **yaml-cpp** (and all dependencies) has been installed correctly.

**Comment by pangchenglin** [comment]
Thanks for your answer！！！@Ethan-Zhou 
I add “ find_package(yaml-cpp REQUIRED)” to CMakeList.txt and compile success.

But when I run "roslaunch esvo_time_surface stereo_time_surface.launch" , some error happened.
![image](https://user-images.githubusercontent.com/30286312/94358128-53430c80-00d1-11eb-9665-0e5044cd2634.png)

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

[rqt_gui-5] process has died [pid 20329, exit code -11, cmd /opt/ros/kinetic/lib/rqt_gui/rqt_gui --perspective-file /home/pclin/esvo_ws/src/ESVO/esvo_time_surface/esvo_time_surface.perspective __name:=rqt_gui __log:=/home/pclin/.ros/log/9ebdcc34-008d-11eb-9b9d-8cec4bc183d8/rqt_gui-5.log].
log file: /home/pclin/.ros/log/9ebdcc34-008d-11eb-9b9d-8cec4bc183d8/rqt_gui-5*.log

My computer is running on Ubuntu 16.04 and ROS Kinetic.How to solve this problem?
Look forward to your reply！
Thank a lot！And I appreciate your job on event camera ！

**Comment by Ethan-Zhou** [comment]
Hi @pangchenglin 

I googled and could not find the same problem as you came across. It looks like something is wrong with rqt. Can you run other ROS turorial node (with rqt) successfully? If not, it indicates that some necessary packages are missing in your ROS.

**Comment by pangchenglin** [comment]
Hi @Ethan-Zhou 
I test the hukst_lab.bag,But when I test upenn_indoor_flying1.bag and rpg_bin.bag ,the esvo_core will died because of esvo_mapping,like this:
![image](https://user-images.githubusercontent.com/30286312/94361270-9909d000-00e5-11eb-8271-9251b6484918.png)
Is it because of something wrong with me？？？
Thank you again ！！！

**Comment by Ethan-Zhou** [comment]
Hi @pangchenglin 
If you can run esvo on hkust_lab, you are suppposed to run it on other datasets with no problem as well. Hmm..., did you make any modification, such that the configuration (e.g. calibration, etc) is not correct any longer?
We haven't received similar problems from other testers yet.
