### ISSUE TITLE
Why not considering event polarity

### ISSUE THREAD

**Issue by robin-shaun** [HKUST-Aerial-Robotics/ESVO#11]
Hello, I'm curious about why the time surface doesn't differentiate the event popularity. Is it useless but causing trouble to optimization?

**Comment by Ethan-Zhou** [comment]
Popularity -> polarity?

As we have cliaimed in our ECCV 2018 work, the introduction of polarity would not improve the mapping remarkably, but it may increase the computation burden by a factor of 2.

**Comment by robin-shaun** [comment]
Thanks a lot!
