### ISSUE TITLE
 sudo apt-get install autoconf

### ISSUE THREAD

**Issue by robin-shaun** [HKUST-Aerial-Robotics/ESVO#12]
hello, I think that to install auoreconf, the command should be ` sudo apt-get install autoconf` rather than  ` sudo apt-get install autoreconf`

**Comment by Ethan-Zhou** [comment]
Hi @robin-shaun,
Commands for installing autoreconf maybe not the same on different Ubuntu version.
As can be seen from https://askubuntu.com/a/269423, your suggestion seems correct on Ubuntu 13.04, 14.04, 16.04. For 20.04, the command is slightly different. Anyway, I have modified the readme and inlcude this discussion there.
Cheers,
yi
