### ISSUE TITLE
How can I use two CeleX-5 sensors to record my dataset?

### ISSUE THREAD

**Issue by aobi12138** [HKUST-Aerial-Robotics/ESVO#13]
I have two CeleX-5 sensors. When I connect them with my computer, I find I am not able to distinguish them because they have the same VID and PID. They are different with the traditional cameras which are controlled by "VedioCapture capture(0);" and "VedioCapture capture(1);" . I have no idea about how to record stereo datasets for the two CeleX-5 sensors. Can you give me some advice? The following picture shows how to make a monocular sensor work. Thank you！
![image](https://user-images.githubusercontent.com/28434475/111455944-5f8b5680-8751-11eb-92fc-29b063d10d15.png)

**Comment by gogojjh** [comment]
A possible solution is that each camera has its unique ID. Could you try to set them as specific ports and then explicitly indicate them in the code?

**Comment by Ethan-Zhou** [comment]
Hi @aobi12138,
I do not have CeleX devices. Please contact their technicians for advices on device synchronization. If you've already know the solution, please share it here with whom need it. Then we can close this issue. Thx!
