### ISSUE TITLE
lack of rostopic 

### ISSUE THREAD

**Issue by tyutnwpuzw** [HKUST-Aerial-Robotics/ESVO#16]
Excuse me ,Dr zhou,i use davis346 to record my own rosbag for ESVO,but there is not a rostipic named /optitrack/davis_stereo.
if this rostopic necessary?
if it is necessary,  i want to ask how do you get this rostopic?thank you.

**Comment by Ethan-Zhou** [comment]
Hi, `/optitrack/davis_stereo` refers to the topic name of Groundtruth trajectory. It is only used by either MVS mode or online evaluation. It is not necessary if you are not using above two features.

**Comment by tyutnwpuzw** [comment]
Hi, thanks for your reply. Can I understand, if i want to run this code with my own DAVIS346 in real time, this topic is necessary?
