### ISSUE TITLE
in real time problems

### ISSUE THREAD

**Issue by tyutnwpuzw** [HKUST-Aerial-Robotics/ESVO#17]
Excuse me again,Dr,zhou.
i want to run this code with my own DAVIS346 in real time,but i got some problems.
The code is runing and no error occur,but there are not result of mapping and tracking ,As shown in the figure below。
i guess the node of tracking and mapping is not running ,so i want to you give me some suggesstions ,thank you.
![Screenshot from 2021-12-02 22-29-52](https://user-images.githubusercontent.com/87970735/144441703-5c9e3a83-f473-4ccb-a3b6-0f7095df3e01.png)

**Comment by Ethan-Zhou** [comment]
Could you please show me TS_left and TS_right running with no problem? Then we can diagnose what was going wrong there， OK？

**Comment by tyutnwpuzw** [comment]
Hi, Dr,zhou,thanks for your reply.
The following images were taken using the event camera to run two programs (ESvo_time_surface and ESvo_core) in real time:
![Screenshot from 2021-12-03 10-21-39](https://user-images.githubusercontent.com/87970735/144535754-a06f0f10-e8ec-49a3-be95-100cb6aedf5f.png)
![Screenshot from 2021-12-03 10-28-43](https://user-images.githubusercontent.com/87970735/144535781-0761cb2d-72c1-4582-984b-7faa6d07d920.png)
![Screenshot from 2021-12-03 10-34-18](https://user-images.githubusercontent.com/87970735/144535792-217086f0-acd0-42ab-8144-0f81ed915a7d.png)
These are the screenshots of running the program, or do you need rosbag or video? Please kindly help to analyze it and look forward to your reply

**Comment by Ethan-Zhou** [comment]
Hi,
Two questions:
1) Have you calibrated your stereo cam? And have you updated the correct calibration parameters?
2) Was the stereo cam static? Why cannot I see background structure on the time surfaces?

**Comment by tyutnwpuzw** [comment]
Dr.zhou ,thank you for your reply.I find that i don't updated the correct calibration parameters ,so i will calibrated my stereo cam this time and chenk the result again,so please don't close the issue,I'll get back to you with the results after the trial.,thank you for your reply again .

**Comment by tyutnwpuzw** [comment]
>

**Comment by tyutnwpuzw** [comment]
hey, Dr Zhou. In the test stage, the rviz run well when we use a simple environment bag recorded by ourselves, however ,the rviz shut down when tested in a little complex environment.
how can i run this progrem in a complex environment?Even if the rebuild doesn't work very well, what parameters can we change to keep the program from crashing?
![Screenshot from 2021-12-03 22-36-16](https://user-images.githubusercontent.com/87970735/144621116-b256ee49-0003-431a-b79d-823518e6a4a4.png)

**Comment by tyutnwpuzw** [comment]
When we call the event camera in real time and run this program, there will be a warning in the terminal, as shown in the picture below.

（2）Do these parameters have any impact? If so, how should we solve them?
![Screenshot from 2021-12-03 22-49-21](https://user-images.githubusercontent.com/87970735/144622638-b9a3c626-06d4-40de-a105-c9fdd495651d.png)



（3）Which method do you use for binocular calibration of the event camera? We can't calibrate it by using the dual target calibration method on the ROS official website.

**Comment by Ethan-Zhou** [comment]
(1) I did not get what's your problem. What did you mean by a complex environment?
(2) You may assign those parameters in the yaml files otherwise they would be set to default values.
(3) It seems that the calibration has not been fixed. Please refer to issue #19. This may cause the unknown problem in (1).
