### ISSUE TITLE
How to calibrate stereo camera

### ISSUE THREAD

**Issue by Wang-Zhiliang** [HKUST-Aerial-Robotics/ESVO#19]
Hello, when I used this project, I noticed that I need to use my own stereo camera calibration parameters. I used ROS monocular camera calibration program to calibrate the two cameras separately, but found that the required calibration file still needed the matrix parameter **T_right_left**, so I would like to ask how to calibrate my stereo camera. Thank you very much!

![Screenshot from 2021-12-04 21-40-40](https://user-images.githubusercontent.com/59563004/144711647-832e0350-e510-4e88-81cc-4f8946e7c627.png)

**Comment by Ethan-Zhou** [comment]
Hi, if you are using a pair of DAVIS 346 cameras, you may use [Kalibr](https://github.com/ethz-asl/kalibr) to do the extrinisic calibration.

**Comment by Wang-Zhiliang** [comment]
hello, I used Kalibr to do the extrinisic calibration. Below are my results:
![image](https://user-images.githubusercontent.com/59563004/144952331-65e27817-839e-44c5-9fe6-4d2e1f6c2153.png)
But how use my calibration to change the calibration data?  
Hope your reply!

**Comment by Ethan-Zhou** [comment]
Once you obtain the intrinsics  and extrinsics, you may further need the rectification matrices. They can be obtained by using OpenCV's[ stereoRectify().](https://docs.opencv.org/3.4/d9/d0c/group__calib3d.html#ga617b1685d4059c6040827800e72ad2b6)

Set the `flag` to CALIB_ZERO_DISPARITY and `alpha` to 1.
