### ISSUE TITLE
esvo mapping issue with opencv in releaseSlot

### ISSUE THREAD

**Issue by AhmedHumais** [HKUST-Aerial-Robotics/ESVO#2]
I am getting following output when I launch mapping with hkust_lab dataset.

================================================================================REQUIRED process [esvo_Mapping-5] has died!
process has died [pid 18557, exit code -11, cmd /home/ahmed/event_ws/devel/lib/esvo_core/esvo_Mapping time_surface_left:=/TS_left time_surface_right:=/TS_right stamped_pose:=/esvo_tracking/pose_pub events_left:=/davis/left/events events_right:=/davis/right/events __name:=esvo_Mapping __log:=/home/ahmed/.ros/log/a18f2d0a-015e-11eb-b197-0433c2687388/esvo_Mapping-5.log].
log file: /home/ahmed/.ros/log/a18f2d0a-015e-11eb-b197-0433c2687388/esvo_Mapping-5*.log
Initiating shutdown!
================================================================================
[rviz-8] killing on exit
[rqt_gui-7] killing on exit
[esvo_Tracking-6] killing on exit
[esvo_Mapping-5] killing on exit
[global_timer-4] killing on exit
[TimeSurface_right-3] killing on exit
[TimeSurface_left-2] killing on exit
OpenCV Error: Assertion failed (tlsSlots.size() > slotIdx) in releaseSlot, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp, line 1092
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp:1092: error: (-215) tlsSlots.size() > slotIdx in function releaseSlot

OpenCV Error: Assertion failed (tlsSlots.size() > slotIdx) in releaseSlot, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp, line 1092
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp:1092: error: (-215) tlsSlots.size() > slotIdx in function releaseSlot

OpenCV Error: Assertion failed (tlsSlots.size() > slotIdx) in releaseSlot, file /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp, line 1092
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv-L2vuMj/opencv-3.2.0+dfsg/modules/core/src/system.cpp:1092: error: (-215) tlsSlots.size() > slotIdx in function releaseSlot

**Comment by Ethan-Zhou** [comment]
Hi @AhmedHumais,

I goolged your problem and it seems that you nay have two versions of OpenCV installed. Besides, as figured out by [this](https://answers.opencv.org/question/226894/opencv-error-assertion-failed-tlsslotssize-slotidx-in-releaseslot/)  , **opencv-3.2.0+dfsg** is somehow not an ideal choice. Actually, I have never seen this version before. Could you please try with a [standard release](https://github.com/opencv/opencv/releases/tag/3.2.0) and see how it goes?

**Comment by AhmedHumais** [comment]
> Hi @AhmedHumais,
> 
> I goolged your problem and it seems that you nay have two versions of OpenCV installed. Besides, as figured out by [this](https://answers.opencv.org/question/226894/opencv-error-assertion-failed-tlsslotssize-slotidx-in-releaseslot/) , **opencv-3.2.0+dfsg** is somehow not an ideal choice. Actually, I have never seen this version before. Could you please try with a [standard release](https://github.com/opencv/opencv/releases/tag/3.2.0) and see how it goes?

Hi @Ethan-Zhou,

Yes the problem was with my OpenCV versions, as I have 2 different versions installed on my system. Just specifying OpenCV version in cmake file solved the problem. Thanks.
