### ISSUE TITLE
esvo_tracking crashes during initialization

### ISSUE THREAD

**Issue by LauZanMo** [HKUST-Aerial-Robotics/ESVO#22]
Hi, I have compiled ESVO on ubuntu 20.04 after refer to @ghoshsuman 's comment [here](https://github.com/HKUST-Aerial-Robotics/ESVO/issues/20#issuecomment-1163412611). But I come across problem when I launch esvo system launch file and it goes like this:
![2022-08-16 21-56-31 的屏幕截图](https://user-images.githubusercontent.com/54791246/184897843-79fc6cf6-f4ee-4a14-b0ba-1389c2b824dd.png)
I try to solve the problem but fail, so I'm posting this Issue in the hope that someone can help me.

**Comment by Ethan-Zhou** [comment]
Hi, to decouple the potential issues, could you please try running the esvo_time_surface node alone? If that succeeds, then please post the error log here again.

**Comment by LauZanMo** [comment]
I debug the project and find it crashes after yaml parse of camera intrinsic matrix. opencv throws out exception that it can not parse camera matrix correctly. Hence I think it is caused by my opencv version. I change my opencv version from 4.5.5 to 4.2.0(ROS version) in cmake and the problem soonly disappears. Thanks for you reply!
