### ISSUE TITLE
something error when I compile

### ISSUE THREAD

**Issue by xiang-1208** [HKUST-Aerial-Robotics/ESVO#26]
when I run：catkin build esvo_time_surface esvo_core
something error happend.
Cloud you please help me to solve this problem? I' dont know how to solve it.

`CMakeFiles/esvo_Tracking.dir/src/esvo_Tracking.cpp.o：在函数‘kindr::minimal::RotationQuaternionTemplate<double>::isValidRotationMatrix(Eigen::Matrix<double, 3, 3, 0, 3, 3> const&, double)’中：
esvo_Tracking.cpp:(.text._ZN5kindr7minimal26RotationQuaternionTemplateIdE21isValidRotationMatrixERKN5Eigen6MatrixIdLi3ELi3ELi0ELi3ELi3EEEd[_ZN5kindr7minimal26RotationQuaternionTemplateIdE21isValidRotationMatrixERKN5Eigen6MatrixIdLi3ELi3ELi0ELi3ELi3EEEd]+0xcb)：对‘google::kLogSiteUninitialized’未定义的引用`

**Comment by TianleXuA** [comment]
I have the same problem ,looking forward to the solution.
