### ISSUE TITLE
Error when using my own rosbag

### ISSUE THREAD

**Issue by AhmedHumais** [HKUST-Aerial-Robotics/ESVO#3]
Every time I run the mapping code on my own dataset the program crashes with the following error. I guess there is some out of bound memory access in the code. Looks like the program is trying to access an element out of the matrix size.

![error_esvo](https://user-images.githubusercontent.com/15062313/96549743-f518dc00-12c0-11eb-9d51-71da2ed31166.png)

----------------------------------------------------------------------------------------------------------------------------------------
`esvo_Mapping: /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:365: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<int, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = int; Eigen::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.`
-----------------------------------------------------------------------------------------------------------------------------------------

This has already been reported before (link below).
[https://github.com/HKUST-Aerial-Robotics/ESVO/issues/1#issuecomment-699609839](url)

Please let me know if you find the solution.

**Note: ** I changed **INIT_SGM_DP_NUM_THRESHOLD** to 120 as I was not getting enough matching points to intialize SGM.

**Comment by Ethan-Zhou** [comment]
Hi @AhmedHumais ,

Thanks for trying ESVO and reporting the problem.

Did you check the resolution parameters? You may use a sensor with different resolution, do you?

Can you successfully run ESVO on other dataset provided by us (e.g. upenn_flying1)?

Tune INIT_SGM_DP_NUM_THRESHOLD is unlikely to cause this happen.

Please let me know how it goes then.

Cheers,

yi

**Comment by Ethan-Zhou** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue at anytime. Thanks.
