### ISSUE TITLE
about time surface 

### ISSUE THREAD

**Issue by Jee-King** [HKUST-Aerial-Robotics/ESVO#8]
Hi, thanks for your great work!
The time surface is computed in a fixed neighborhood (2R+1 x 2R+1) in the original paper (_HOTs_).
The neighborhood in your work is the whole image, right?

**Comment by Ethan-Zhou** [comment]
Yes, the TS is computed on the whole image plane in our work.

**Comment by Jee-King** [comment]
Why do you compute TS on the whole image plane? Would it be better? Or for your work can only be calculated on the whole image plane?

**Comment by Ethan-Zhou** [comment]
The time surface is just a way to represent the spatio-temporal signature in the 2D image plage. Strictlly, it is defined at each pixel coordinate given a timestamp, with an exponential decay kernel.
In the HOTs paper, they may want to emphasize the asynchronous nature of event cameras, therefore, the TS is defined inside a patch (2R + 1) x (2R +1) for each upcoming event. But seen from Fig.2 in that paper, you would see the time surface is actually calculated on the whole image plane.
To conclude, you can do whatever you want depending on your design.

**Comment by Jee-King** [comment]
Thanks for your reply! :blush:
