### ISSUE TITLE
esvo_mapping

### ISSUE THREAD

**Issue by jsz0913** [HKUST-Aerial-Robotics/ESVO#9]
hello，
   In the depthproblem.cpp,why don't need fjac？

**Comment by Ethan-Zhou** [comment]
Could you please detail the question?

**Comment by jsz0913** [comment]
In the depth problem, I don't know how the inverse depth value is optimized, or is there any information about the use of Leninberg method in the Eigen Unsupport Module？

Thank you for your attention to my question

**Comment by Ethan-Zhou** [comment]
The inverse depth estimation problem is defined in DepthProblem.cpp (see operator()) and solved in DepthProblemSolver.cpp. If you would like to learn how to use LM solver with Eigen, there are a lot references online.

**Comment by jsz0913** [comment]
thanks
